namespace Riverside.ComponentModel
{
    public static class Libraries
    {
        public const string Shell32 = "shell32.dll"; // Shell API
        public const string Kernel32 = "kernel32.dll"; // Windows Kernel
        public const string User32 = "user32.dll"; // Windows User
        public const string AdvancedWin32 = "advapi32.dll"; // Advanced Windows API
        public const string GraphicsDeviceInterface = "gdi32.dll"; // Graphics Device Interface
        public const string ObjectLinkingEmbedding = "ole32.dll"; // Object Linking and Embedding
        public const string WindowsSockets = "ws2_32.dll"; // Windows Sockets
        public const string CryptographicAPI = "crypt32.dll"; // Cryptographic API
        public const string CRuntimeLibrary = "msvcrt.dll"; // C Runtime Library
        public const string CommonDialogs = "comdlg32.dll"; // Common Dialogs
        public const string ShellLightweightUtilityLibrary = "shlwapi.dll"; // Shell Lightweight Utility Library
        public const string WindowsPrinting = "winspool.drv"; // Windows Printing
        public const string NetworkAPI = "netapi32.dll"; // Network API
        public const string IPHelperAPI = "iphlpapi.dll"; // IP Helper API
        public const string ProcessStatusAPI = "psapi.dll"; // Process Status API
        public const string DebuggingHelpers = "dbghelp.dll"; // Debugging Helpers
        public const string VersionInformation = "version.dll"; // Version Information
        public const string WindowsNTLayer = "ntdll.dll"; // Windows NT Layer
        public const string MultipleProviderRouter = "mpr.dll"; // Multiple Provider Router
        public const string InternetAPI = "wininet.dll"; // Internet API
        public const string LDAPAPI = "wldap32.dll"; // LDAP API
        public const string URLMoniker = "urlmon.dll"; // URL Moniker
        public const string SetupAPI = "setupapi.dll"; // Setup API
        public const string WindowsSocketsHelper = "ws2help.dll"; // Windows Sockets Helper
        public const string WindowsSocketsTCPIP = "wshtcpip.dll"; // Windows Sockets TCP/IP
        public const string RPCRuntime = "rpcrt4.dll"; // RPC Runtime
        public const string WindowsSocketsExtensions = "mswsock.dll"; // Windows Sockets Extensions
        public const string VCPlusPlusRuntime140 = "msvcp140.dll"; // VC++ Runtime 140
        public const string MFCPlusPlus140 = "mfc140u.dll"; // MFC++ 140
        public const string VCPlusPlusRuntime120 = "msvcp120.dll"; // VC++ Runtime 120
        public const string DesktopWindowManager = "dwmapi.dll"; // Desktop Window Manager
        public const string Direct3D11 = "d3d11.dll"; // Direct3D 11
        public const string Direct3D12 = "d3d12.dll"; // Direct3D 12
        public const string Direct3D9 = "d3d9.dll"; // Direct3D 9
        public const string DirectXGraphicsInfrastructure = "dxgi.dll"; // DirectX Graphics Infrastructure
        public const string WindowsMultimedia = "winmm.dll"; // Windows Multimedia
        public const string InputMethodManager = "imm32.dll"; // Input Method Manager
        public const string OpenGL = "opengl32.dll"; // OpenGL
        public const string OpenGLUtility = "glu32.dll"; // OpenGL Utility
        public const string OpenCL = "OpenCL.dll"; // OpenCL
        public const string VCPlusPlusRuntimeLib = "vcruntime140.dll"; // VC++ Runtime Library
        public const string XInput14 = "xinput1_4.dll"; // XInput 1.4
        public const string XInput910 = "xinput9_1_0.dll"; // XInput 9.1.0
        public const string XInput13 = "xinput1_3.dll"; // XInput 1.3
        public const string DirectSound = "dsound.dll"; // DirectSound
        public const string DirectInput8 = "dinput8.dll"; // DirectInput 8
        public const string MediaFoundationPlatform = "mfplat.dll"; // Media Foundation Platform
        public const string MediaFoundationReadWrite = "mfreadwrite.dll"; // Media Foundation ReadWrite
        public const string MediaFoundationUUID = "mfuuid.dll"; // Media Foundation UUID
        public const string AudioSession = "AudioSes.dll"; // Audio Session
        public const string AVRT = "avrt.dll"; // AVRT
        public const string WindowsImageAcquisition = "wiaut.dll"; // Windows Image Acquisition
        public const string WindowsMediaFormat = "wmvcore.dll"; // Windows Media Format
        public const string WindowsMediaPlayer = "wmp.dll"; // Windows Media Player
        public const string WindowsCodecs = "windowscodecs.dll"; // Windows Codecs
        public const string DirectShow = "quartz.dll"; // DirectShow
        public const string DirectMusic = "dmusic.dll"; // DirectMusic
        public const string DirectPlay = "dpnet.dll"; // DirectPlay
        public const string DirectDraw = "ddraw.dll"; // DirectDraw
        public const string DirectAccess = "daccess.dll"; // DirectAccess
        public const string NetworkDiagnostics = "netdiagfx.dll"; // Network Diagnostics
        public const string BluetoothAPIs = "bthprops.cpl"; // Bluetooth APIs
        public const string WindowsPortableDevices = "wpdmtp.dll"; // Windows Portable Devices
        public const string WindowsPerformanceCounter = "pdh.dll"; // Windows Performance Counter
        public const string WindowsMessaging = "winmm.dll"; // Windows Messaging
        public const string WindowsScriptingHost = "wshom.ocx"; // Windows Scripting Host
        public const string WindowsHelp = "help.dll"; // Windows Help
        public const string WindowsWebServices = "webservices.dll"; // Windows Web Services
        public const string WindowsDataAccessComponents = "msado15.dll"; // Windows Data Access Components
        public const string WindowsManagementInstrumentation = "wmi.dll"; // Windows Management Instrumentation
        public const string WindowsSecurityManager = "secur32.dll"; // Windows Security Manager
        public const string WindowsAudioCore = "audioses.dll"; // Windows Audio Core
        public const string WindowsFirewallAPI = "firewallapi.dll"; // Windows Firewall API
        public const string WindowsHTTPServices = "winhttp.dll"; // Windows HTTP Services
        public const string WindowsInstrumentation = "instrumentation.dll"; // Windows Instrumentation
        public const string WindowsMobileAPI = "wmdmps.dll"; // Windows Mobile API
        public const string WindowsProtectedStorage = "pstorec.dll"; // Windows Protected Storage
        public const string WindowsUtilityLibrary = "utility.dll"; // Windows Utility Library
        public const string WindowsWebBrowserControl = "mshtml.dll"; // Windows Web Browser Control
        public const string WindowsXMLEditor = "msxml.dll"; // Windows XML Editor
        public const string WindowsMediaFoundation = "mf.dll"; // Windows Media Foundation
        public const string WindowsImageProcessing = "wimgapi.dll"; // Windows Image Processing
        public const string WindowsBioAPI = "winbio.dll"; // Windows Biometric API
        public const string WindowsAuthentication = "authz.dll"; // Windows Authentication
        public const string WindowsBackupAPI = "wbengine.dll"; // Windows Backup API
        public const string WindowsEventLog = "wevtapi.dll"; // Windows Event Log
        public const string WindowsNetworkList = "nlaapi.dll"; // Windows Network List
        public const string WindowsPowerShell = "powershell.exe"; // Windows PowerShell
        public const string WindowsRemoteManagement = "wsman.dll"; // Windows Remote Management
        public const string WindowsResourceManager = "resutils.dll"; // Windows Resource Manager
        public const string WindowsSpeechAPI = "sapi.dll"; // Windows Speech API
        public const string WindowsStorageManagement = "srm.dll"; // Windows Storage Management
        public const string WindowsSyncCenter = "syncmgr.dll"; // Windows Sync Center
        public const string WindowsTaskScheduler = "taskschd.dll"; // Windows Task Scheduler
        public const string WindowsTelemetry = "telemetry.dll"; // Windows Telemetry
        public const string WindowsUIAutomation = "uiautomationcore.dll"; // Windows UI Automation
        public const string WindowsVirtualDisk = "virtdisk.dll"; // Windows Virtual Disk
        public const string WindowsVolumeShadowCopy = "vssapi.dll"; // Windows Volume Shadow Copy
        public const string WindowsWebDAV = "webdav.dll"; // Windows WebDAV
        public const string WindowsWinHTTP = "winhttp.dll"; // Windows WinHTTP
        public const string WindowsWLAN = "wlanapi.dll"; // Windows WLAN
        public const string WindowsWMI = "wmiutils.dll"; // Windows WMI
        public const string WindowsWOW64 = "wow64.dll"; // Windows WOW64
        public const string WindowsXMLLite = "xmllite.dll"; // Windows XML Lite

        public const string ShellCore = "shcore.dll"; // Shell Core
        public const string CommonControls = "comctl32.dll"; // Common Controls
    }
}
