name: CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'eng/CurrentVersion.props'

jobs:
  build:
    name: Publish
    runs-on: windows-latest
    environment: NuGet
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
    env:
        WORKING_DIR: ${{ github.workspace }}
        SOLUTION_PATH: '${{ github.workspace }}\CubeKit.slnx'
        HEAD_PROJECTS_DIR: '${{ github.workspace }}\src\platforms'
        HEAD_EXTENSIONS_DIR: '${{ github.workspace }}\src\extensions'
        CONFIGURATION: ${{ matrix.configuration }}
        ARCHITECTURE: 'Any CPU'

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Restore project
      shell: pwsh
      run: |
          msbuild $env:SOLUTION_PATH `
            -t:Restore `
            -p:Platform=$env:ARCHITECTURE `
            -p:Configuration=$env:CONFIGURATION

    - name: Build CubeKit
      run: |
          msbuild "$env:SOLUTION_PATH" `
            -t:Build `
            -p:Configuration=$env:CONFIGURATION

    - name: Package CubeKit
      run: |
          msbuild "$env:SOLUTION_PATH" `
            -t:Build `
            -p:Configuration=Release `
            -p:PackageOutputPath="$env:WORKING_DIR\bin"

    - name: Publish packages to NuGet
      run: dotnet nuget push ./bin/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Publish symbols to NuGet
      run: dotnet nuget push ./bin/*.snupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
